### ISSUE TITLE
Publish doesn't do git add

### ISSUE THREAD

**Issue by h0tk3y** [layerhq/gradle-git-repo-plugin#18]
When I perform `publish` task no files are added to git staging area in the local repo (that which is in `~/.gitRepos`), and after `publishToGithub` there's an empty commit (0 files changed). However, if I do `git add --all` inbetween `publish` and `publishToGithub` all the changes are pushed correctly.
Is it a bug or may I have mistaken somewhere?

**Comment by drapp** [comment]
Yes, there is a bug, this issue was logged on the subject
https://github.com/layerhq/gradle-git-repo-plugin/issues/15
I suspect changing this `*` to a `.` would fix it, but I need to test the fix
https://github.com/layerhq/gradle-git-repo-plugin/blob/master/src/main/groovy/com/layer/gradle/gitrepo/GitRepoPlugin.groovy#L53
